file_cats = {
    "audio": ["mp3", "wav", "raw", "wma", "mid", "midi"],
    "video": ["mp4", "mpg", "mpeg", "avi", "mov", "flv", "mkv", "mwv", "m4v", "h264"],
    "images": [
        "png",
        "jpg",
        "jpeg",
        "gif",
        "svg",
        "bmp",
        "psd",
        "svg",
        "tiff",
        "tif",
        "heic",
    ],
    "compressed": ["zip", "z", "7z", "rar", "tar", "gz", "rpm", "pkg", "deb"],
    "installation": ["dmg", "exe", "iso"],
    "csvs":["csv"],
    "docs": [
        "txt",
        "ods",
        "doc",
        "docx",
        "html",
        "odt",
        "tex",
        "ppt",
        "pptx",
        "log",
    ],
    "pdfs": ["pdf"],
    "excel_files":["xls","xlsx"],
    "sql":['sql','sqlite'],
    "markdown":["md"],
    "python": ["py", "ipynb"],
    "ableton": ["als"],
}

